SOURCES_SHARED := clear_list.c copy_n_list.c find_first.c insert_before.c \
insert_list_start.c new_node.c remove_n_nodes.c clear_node.c cut_node.c \
insert_after.c insert_list_end.c new_list.c print_list.c remove_node.c

include ../../common.mk
