SOURCES_STANDARD = ft_printf.c
SOURCES_SHARED = ft_print_character.c ft_print_string.c \
ft_print_void_pointer.c ft_print_integer.c ft_ultoa_base.c \
ft_print_unsigned_decimal.c ft_print_hexadecimal_lower.c \
ft_print_hexadecimal_upper.c
SOURCES_BONUS = 

include ../../common.mk
